import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Odyssey Front End</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col min-h-screen overflow-hidden">
        <main className="flex-grow">
          <section className="relative flex h-screen items-center justify-center">
            <div className="max-w-6xl mx-auto px-4 sm:px-6">
              <div className="pt-32 pb-12 md:pt-40 md:pb-20">
                <div className="text-center pb-12 md:pb-16">
                  <h1
                    className="text-5xl md:text-6xl font-extrabold leading-tighter tracking-tighter mb-4 aos-init aos-animate"
                    data-aos="zoom-y-out"
                  >
                    Odesey - Document
                    <span className="ml-4 bg-clip-text text-transparent bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500">
                      your journey
                    </span>
                  </h1>

                  <div className="max-w-3xl mx-auto">
                    <p className="text-xl text-gray-600 mb-8 aos-init aos-animate"></p>
                    <div className="max-w-xs mx-auto sm:max-w-none sm:flex sm:justify-center aos-init aos-animate">
                      <div>
                        <Link
                          className="btn text-white bg-gray-900 hover:bg-gray-800 w-full sm:w-auto sm:ml-4 bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500"
                          href="/profile"
                        >
                          Get Started
                        </Link>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </main>
      </div>
    </div>
  )
}
